### ISSUE TITLE
Need help !

### ISSUE THREAD

**Issue by SudoDios** [luchev/uni-assembly#1]
I am looking for a super fast library for encrypt large strings with key in C++.
Do you know anything?

**Comment by luchev** [comment]
Hi, I have not evaluated different C++ encryption libraries. This repo was me hacking away at some assembly and is definitely not using secure encryption algorithms, so please do not use it in any serious projects.
I suggest checking out [Crypto++](https://cryptopp.com/), which supposedly implements AES-GCM with CPU optimizations.
I have not used the library myself, but it sounds like they know what they're doing.

**Comment by SudoDios** [comment]
OK, thank you!
